export { default as Header } from './header/Header';
export { default as Sidebar } from './sidebar/Sidebar';
export { default as Profile } from './profile/Profile';
export { default as About } from './about/About';
export { default as WideCardA } from './wideCardA/WideCard'; 
export { default as WideCardB } from './wideCardB/WideCard';
export { default as Background } from './background/Background';
export { default as Elements } from './elements/Elements'; 
export { default as LongCard } from './longCard/LongCard';